name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MAJOR_VERSION: 0
  MINOR_VERSION: 1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: '${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.GITHUB_RUN_ID }}'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release --no-build -p:Version=$VERSION
    - name: Publish
      run: dotnet nuget push bin\Release\ResponsibleChains.$VERSION.nupkg --api-key $NUGET_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate